---
title: "R Notebook"
output: html_notebook
---

```{r}
library("lhs")
library("tidyverse")
library("RColorBrewer")
```

```{r}
read_data <- function(type, size) {
  data <- c()
  
  lines <- read_lines(Sys.glob(paste0(type, "*", size, "*")))
  for (i in 1:length(lines)){
    if (length(grep("sort_data", lines[i])) != 1 & length(grep("validation", lines[i])) != 1) {
      data <- c(data, lines[i])
    }
  }
  
  return (read_delim(paste(data, collapse = "\n"), delim = ";", col_names = FALSE))
}
```


```{r}
load_bp <- function(type, size) {
  df <- read_data(type, size)
  
  df <- df %>%
    filter(X3 < 10) %>%
    group_by(X3, X5) %>%
    summarise(
        Time = sum(X7)
    ) %>% 
    group_by(X3) %>%
    summarise(
      Max = max(Time),
      Min = min(Time),
      Mean = mean(Time),
      Stdv = sd(Time)
    ) %>%
    mutate(
      Bench = paste0(type, " <", size,">")
    )
  
  return (df)
}
```


```{r}
load_h <- function(type, size) {
  df <- read_data(type, size)
  
  df <- df %>%
      filter(X3 < 10) %>%
      group_by(X3, X8) %>%
      summarise(
        Max = max(X7),
        Min = min(X7),
        Mean = mean(X7),
        Stdv = sd(X7)
      ) %>%
      mutate(
        Bench = paste0(type, " <", size,">")
      )
  
  return (df)
}
```

```{r}
rbind(load_h("pdigest", "1M"), load_h("raw", "1M")) %>% 
  ggplot(aes(x = X3, y = Mean)) +
  geom_bar(aes(fill = X8), stat="identity") + 
  scale_x_continuous(breaks = round(seq(0, 10, by = 1), 2)) + 
  facet_wrap(. ~ Bench , scales = "fixed", ncol = 1) + 
  theme_bw() + 
  xlab("Quadtree Depth") + 
  ylab("Time") + 
  labs(fill = "Query Steps") + 
  scale_fill_manual(values = brewer.pal(3, "Set1"), labels = c("Aggregation", "Intersection", "Selection"))
  # theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
```



```{r}
rbind(
    load_bp("pdigest", "1M"),
    load_bp("raw", "1M")
  ) %>% 
  ggplot(aes(x = Bench, y = Mean)) + 
    geom_boxplot(aes(colour = Bench)) + 
    coord_flip()
```

```{r}
rbind(
    load_bp("pdigest", "5M"),
    load_bp("raw", "5M")
  ) %>% 
  ggplot(aes(x = X3, y = Mean, colour = Bench)) +
    geom_line(aes(x = X3, y = Mean, colour = Bench), size = 1) +
    scale_x_continuous(breaks = round(seq(0, 10, by = 1), 2)) + 
    # scale_colour_brewer(palette = "Set1") +
    theme_bw() + 
    xlab("Quadtree Depth") + 
    ylab("Time") + 
    labs(fill = "Query Steps")
    # geom_errorbar(aes(ymin = Mean - Stdv, ymax = Mean + Stdv), width = 2, position=position_dodge(0.05))
    # scale_y_continuous(limits = c(0, 300))
    # scale_y_log10()
```

