---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidyverse")
library("lhs")
```

```{r}
file <- "pdigest_20180719-113546_gaussian.csv"
bench <- "p-digest"

pdigest <- read_delim(file, delim = ";", col_names = FALSE)

pdigest <- pdigest %>%
    group_by(X3, X5) %>%
    summarise(Time = sum(X7)) %>%
    mutate(
    Bench = bench
  )
```

```{r}
file <- "raw_20180719-113546_gaussian.csv"
bench <- "raw"

data <- c()

lines <- read_lines(file)
for (i in 1:length(lines)){
  if (length(grep("sort_data", lines[i])) != 1) {
    data <- c(data, lines[i])
  }
}

raw <- read_delim(paste(data, collapse = "\n"), delim = ";", col_names = FALSE)

raw <- raw %>%
    group_by(X3, X5) %>%
    summarise(Time = sum(X7)) %>%
    mutate(
    Bench = bench
  )
```



```{r include=FALSE}
data <- rbind(pdigest, raw)
```

```{r}
df <- data %>%
  group_by(Bench) %>%
  summarise(
    Max = max(Time),
    Min = min(Time),
    Mean = mean(Time),
    Stdv = sd(Time)
  ) %>% filter(!is.na(Max))


df_121453 <- df %>% filter(Bench == "121453")
df_092927 <- df %>% filter(Bench == "092927")

min_max_121453 <- which.min(df_121453$Max)
min_max_092927 <- which.min(df_092927$Max)

min_mean_121453 <- which.min(df_121453$Mean)
min_mean_092927 <- which.min(df_092927$Mean)

df %>% ggplot() +
  geom_line(aes(x = Factor, y = Max, colour = Bench)) +
  # geom_errorbar(aes(ymin= Mean - Stdv, ymax = Mean + Stdv, x = Factor), width=.1) +
  geom_vline(xintercept = 5, linetype = 2, colour = "black") +
  geom_label(aes(x = 5, y = 7500, label = 'default')) +
  
  geom_vline(xintercept = min_max_121453, linetype = 2, colour = "blue") +
  geom_label(aes(x = min_max_121453, y = 7500, label = '<121453>\nmin(time)')) +
  
  geom_vline(xintercept = min_max_092927, linetype = 2, colour = "red") +
  geom_label(aes(x = min_max_092927, y = 6000, label = '<092927>\nmin(time)')) +
    
  theme_bw() +
  scale_x_continuous(limits = c(0, 100), breaks = round(seq(0, 100, by = 5), 2)) +
  scale_y_continuous(limits = c(3500, 9500), breaks = round(seq(3500, 9500, by = 500), 2))

df %>% ggplot() +
  geom_line(aes(x = Factor, y = Mean, colour = Bench)) +
  # geom_errorbar(aes(ymin= Mean - Stdv, ymax = Mean + Stdv, x = Factor), width=.1) +
  geom_vline(xintercept = 5, linetype = 2, colour = "black") +
  geom_label(aes(x = 5, y = 1000, label = 'default')) +
  
  geom_vline(xintercept = min_mean_121453, linetype = 2, colour = "darkcyan") +
  geom_label(aes(x = min_mean_121453, y = 1000, label = '<121453>\nmin(time)')) +
  
  geom_vline(xintercept = min_mean_092927, linetype = 2, colour = "red") +
  geom_label(aes(x = min_mean_092927, y = 800, label = '<092927>\nmin(time)')) +
    
  theme_bw() +
  scale_x_continuous(limits = c(0, 100), breaks = round(seq(0, 100, by = 5), 2)) +
  scale_y_continuous(limits = c(550, 1500), breaks = round(seq(550, 1500, by = 50), 2))
```

```{r}
data %>% 
  filter(Bench == "raw_region" | Bench == "raw_tile") %>%
  ggplot(aes(x = Time)) + 
    geom_histogram(aes(y = cumsum(..count..)), binwidth = 1, boundary = 0) + 
    ggtitle("raw")

data %>% 
  filter(Bench == "pdigest_region" | Bench == "pdigest_tile") %>%
  ggplot(aes(x = Time)) + 
    geom_histogram(aes(y = cumsum(..count..)), binwidth = 1, boundary = 0) + 
    ggtitle("pdigest")
```

```{r}
data
```


```{r}
df <- data %>%
  group_by(X3, Bench) %>%
  summarise(
    Max = max(Time),
    Min = min(Time),
    Mean = mean(Time),
    Stdv = sd(Time)
  ) %>% filter(!is.na(Max))

data %>% 
  ggplot(aes(x = Bench, y = Time)) + 
    geom_boxplot(aes(colour = Bench)) + 
    coord_flip()

df

df %>% 
  # filter(Bench == "p-digest") %>%
  ggplot(aes(x = X3, y = Mean, colour = Bench)) +
    geom_line(aes(x = X3, y = Mean, colour = Bench)) #+
    #geom_errorbar(aes(ymin = Mean - Stdv, ymax = Mean + Stdv), width = 2, position=position_dodge(0.05)) +
    # scale_y_continuous(limits = c(0, 40), breaks = round(seq(0, 40, by = 500), 2))
    # scale_y_log10()
  
```

