---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidyverse")
```

```{r}
f <- function(df) {
  df %>%
    group_by(X3, X6) %>%
    summarise(Mean = mean(X5), Min = min(X5), Max = max(X5), Stdv = sd(X5))
    
  df <- df %>%
    group_by(X3) %>%
    summarise(Time = sum(X5) / 3)
  
  df %>% filter(Time <= 1)
  df %>% filter(Time > 1 & Time <= 10)
  df %>% filter(Time > 10 & Time <= 20)
  df %>% filter(Time > 20 & Time <= 30)
  df %>% filter(Time > 30 & Time <= 40)
  df %>% filter(Time > 40)
  
  df %>% summarise(Max = max(Time), Min = min(Time), Mean = mean(Time), Stdv = sd(Time))
}
```

```{r}
brightkite <- read_delim(file = "disabled_20180708-164037_nc_brightkite-count.csv", delim = ";", col_names = FALSE)

gowalla <- read_delim(file = "disabled_20180708-164037_nc_gowalla-count.csv", delim = ";", col_names = FALSE)

flights <- read_delim(file = "disabled_20180708-164037_nc_on_time_performance-count.csv", delim = ";", col_names = FALSE)

twitter <- read_delim(file = "disabled_20180708-164037_nc_twitter-small-count.csv", delim = ";", col_names = FALSE)

f(brightkite)
f(gowalla)
f(flights)
f(twitter)
```

```{r}
df <- brightkite

brightkite %>% filter(X3 == 1037)

  df %>%
    group_by(X3, X6) %>%
    summarise(Mean = mean(X5), Min = min(X5), Max = max(X5), Stdv = sd(X5))
    
  df <- df %>%
    group_by(X3) %>%
    summarise(Time = sum(X5) / 3)
  
  df %>% filter(Time <= 1)
  df %>% filter(Time > 1 & Time <= 10)
  df %>% filter(Time > 10 & Time <= 20)
  df %>% filter(Time > 20 & Time <= 30)
  df %>% filter(Time > 30 & Time <= 40)
  df %>% filter(Time > 40)
  
  df %>% filter(Time > 1000)
  
  df %>% summarise(Max = max(Time), Min = min(Time), Mean = mean(Time), Stdv = sd(Time))
```





