---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidyverse")
library("lhs")
```

```{r include=FALSE}
f <- function(bench) {
  data <- NA
  
  for (i in seq(100)) {
    files <- list.files(path = "./", pattern = paste0(bench, "_", i, "_"))
    for (file in files) {
      df <- read_delim(file, delim = ";", col_names = FALSE)
      df <- df %>%
        group_by(X3) %>%
        summarise(Time = sum(X7) / 3) %>%
        mutate(
          Factor = i,
          Bench = bench
        )
      
      data <- rbind(data, df) 
    }
  }
  data <- data %>% filter(!is.na(Time))
  
  return(data)
}

data_121453 <- f("121453")
data_092927 <- f("092927")

data <- rbind(data_121453, data_092927)
```

```{r}
raw <- NA

files <- list.files(path = "./", pattern = paste0("raw"))
for (file in files) {
  df <- read_delim(file, delim = ";", col_names = FALSE)
  df <- df %>%
    group_by(X3) %>%
    summarise(Time = sum(X7) / 3) %>%
    mutate(
      Bench = "raw",
      Factor = NA
    )
  
  raw <- rbind(raw, df) 
}

raw <- raw %>% filter(!is.na(Time))

raw <- raw[1:100,]
```


```{r}
df <- data %>%
  group_by(Factor, Bench) %>%
  summarise(
    Max = max(Time),
    Min = min(Time),
    Mean = mean(Time),
    Stdv = sd(Time)
  ) %>% filter(!is.na(Max))


df_121453 <- df %>% filter(Bench == "121453")
df_092927 <- df %>% filter(Bench == "092927")

min_max_121453 <- which.min(df_121453$Max)
min_max_092927 <- which.min(df_092927$Max)

min_mean_121453 <- which.min(df_121453$Mean)
min_mean_092927 <- which.min(df_092927$Mean)

df %>% ggplot() +
  geom_line(aes(x = Factor, y = Max, colour = Bench)) +
  # geom_errorbar(aes(ymin= Mean - Stdv, ymax = Mean + Stdv, x = Factor), width=.1) +
  geom_vline(xintercept = 5, linetype = 2, colour = "black") +
  geom_label(aes(x = 5, y = 7500, label = 'default')) +
  
  geom_vline(xintercept = min_max_121453, linetype = 2, colour = "blue") +
  geom_label(aes(x = min_max_121453, y = 7500, label = '<121453>\nmin(time)')) +
  
  geom_vline(xintercept = min_max_092927, linetype = 2, colour = "red") +
  geom_label(aes(x = min_max_092927, y = 6000, label = '<092927>\nmin(time)')) +
    
  theme_bw() +
  scale_x_continuous(limits = c(0, 100), breaks = round(seq(0, 100, by = 5), 2)) +
  scale_y_continuous(limits = c(3500, 9500), breaks = round(seq(3500, 9500, by = 500), 2))

df %>% ggplot() +
  geom_line(aes(x = Factor, y = Mean, colour = Bench)) +
  # geom_errorbar(aes(ymin= Mean - Stdv, ymax = Mean + Stdv, x = Factor), width=.1) +
  geom_vline(xintercept = 5, linetype = 2, colour = "black") +
  geom_label(aes(x = 5, y = 1000, label = 'default')) +
  
  geom_vline(xintercept = min_mean_121453, linetype = 2, colour = "darkcyan") +
  geom_label(aes(x = min_mean_121453, y = 1000, label = '<121453>\nmin(time)')) +
  
  geom_vline(xintercept = min_mean_092927, linetype = 2, colour = "red") +
  geom_label(aes(x = min_mean_092927, y = 800, label = '<092927>\nmin(time)')) +
    
  theme_bw() +
  scale_x_continuous(limits = c(0, 100), breaks = round(seq(0, 100, by = 5), 2)) +
  scale_y_continuous(limits = c(550, 1500), breaks = round(seq(550, 1500, by = 50), 2))
```

```{r}
data_092927 %>% 
  filter(Factor == min_mean_092927) %>%
  ggplot(aes(x = Time)) + 
    geom_histogram(aes(y = cumsum(..count..)), binwidth = 1, boundary = 0) + 
    ggtitle("092927")

raw %>% 
  ggplot(aes(x = Time)) + 
    geom_histogram(aes(y = cumsum(..count..)), binwidth = 1, boundary = 0) + 
    ggtitle("raw")
```


```{r}
boxplot <- rbind(
    data_121453 %>% filter(Factor == min_mean_121453),
    data_092927 %>% filter(Factor == min_mean_092927),
    raw
  ) 

boxplot %>% 
  ggplot(aes(x = Bench, y = Time)) + 
    geom_boxplot(aes(colour = Bench)) + 
    coord_flip()

boxplot %>% 
  filter(Time <= 40) %>%
  ggplot(aes(x = Bench, y = Time)) + 
    geom_boxplot(aes(colour = Bench)) + 
    #scale_y_continuous(limits = c(1200, 4500), breaks = round(seq(1000, 4500, by = 250), 2)) +
    coord_flip() + 
    ggtitle("Time <= 40ms")

boxplot %>% 
  filter(Time >=1 & Time <= 40) %>%
  ggplot(aes(x = Bench, y = Time)) + 
    geom_boxplot(aes(colour = Bench)) + 
    #scale_y_continuous(limits = c(1200, 4500), breaks = round(seq(1000, 4500, by = 250), 2)) +
    coord_flip() + 
    ggtitle("Time >=1 & Time <= 40")
```


```{r}

data_121453 %>% 
  filter(Factor == min_mean_121453) %>%
  summarise(
    "0%"=quantile(Time, probs=0.0),
    "25%"=quantile(Time, probs=0.25),
    "50%"=quantile(Time, probs=0.5),
    "75%"=quantile(Time, probs=0.75),
    "100%"=quantile(Time, probs=1.0)
  )

data_092927 %>% 
  filter(Factor == min_mean_092927) %>%
  summarise(
    "0%"=quantile(Time, probs=0.0),
    "25%"=quantile(Time, probs=0.25),
    "50%"=quantile(Time, probs=0.5),
    "75%"=quantile(Time, probs=0.75),
    "80%"=quantile(Time, probs=0.8),
    "90%"=quantile(Time, probs=0.9),
    "95%"=quantile(Time, probs=0.95),
    "100%"=quantile(Time, probs=1.0)
  )

raw %>% 
  summarise(
    "0%"=quantile(Time, probs=0.0),
    "25%"=quantile(Time, probs=0.25),
    "50%"=quantile(Time, probs=0.5),
    "75%"=quantile(Time, probs=0.75),
    "80%"=quantile(Time, probs=0.8),
    "90%"=quantile(Time, probs=0.9),
    "95%"=quantile(Time, probs=0.95),
    "100%"=quantile(Time, probs=1.0)
  )
```
```{r}
quantile(df$Time)
```


```{r}
A <- randomLHS(100, 2)
A
```



